### ISSUE TITLE
Not work with Python 3

### ISSUE THREAD

**Issue by skitazaki** [tryggvib/datapackage#28]
Here is the minimum reproduce codes.

```
Python 3.4.2 (default, Oct  9 2014, 21:41:07)
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import datapackage
>>> datapkg = datapackage.DataPackage('http://data.okfn.org/data/cpi/')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/datapackage/datapackage.py", line 108, in __init__
    descriptor = self.get_descriptor()
  File "/root/datapackage/datapackage.py", line 595, in get_descriptor
    json_descriptor = json.loads(str_descriptor)
  File "/usr/local/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

I created the [gist](https://gist.github.com/skitazaki/988f29a5dd0db0d2e25b) to resolve this issue on Python 3.
But, I think that we should use `requests` and/or `six` to support both Python 2 and Python 3 by same codebase. How do you think about depending on other third-party modules?

**Comment by pwalsh** [comment]
Py3 support is being worked on here: https://github.com/tryggvib/datapackage/pull/33

**Comment by tryggvib** [comment]
Python 3 support is now merged into master. Thank you @pwalsh
