### ISSUE TITLE
Adding `resource_class` as a DataPackage attribute

### ISSUE THREAD

**Issue by pwalsh** [tryggvib/datapackage#29]
I was thinking to make a pull request on datapackage to add a `resource_class` attribute, so that inheriting classes do not need to override the `resources` property.

Example of overriding that can be prevented: https://github.com/tryggvib/budgetdatapackage/blob/master/budgetdatapackage/datapackage.py#L30

So we'd have:

```
class DataPackage(Specification):

    resource_class = Resource

    ...
    @resources.setter
    def resources(self, value):
        ...
        if isinstance(single_value, self.resource_class):
            # etc.

```

@tryggvib, WDYT?

**Comment by tryggvib** [comment]
That sounds good. Go ahead :)

**Comment by pwalsh** [comment]
https://github.com/tryggvib/datapackage/pull/30
