### ISSUE TITLE
Setup.py doesn't work

### ISSUE THREAD

**Issue by tryggvib** [tryggvib/datapackage#39]
Running setup.py returns an error:

> error in datapackage setup command: package_data must be a dictionary mapping package names to lists of wildcard patterns

This was introduced in commit 4f49664aed95eac91d8b0a43013f804b6a69790e

**Comment by pwalsh** [comment]
I've just done clean installs with the latest packages from pypi into Py2.7 and Py3.4 virtual environments, and did not encounter this. Is it still an issue?

Looking at the commit, I don't see what was introduced that caused this,  but I am wondering if it may be related to the [unicode literals](https://github.com/tryggvib/datapackage/blob/master/setup.py#L6) import in combination with Py2.7?

**Comment by pwalsh** [comment]
@tryggvib I've confirmed that the unicode literals import is what messes things up on Python 2.x in setup.py
